name: roomsocket
description: Lightweight WebSocket server with room support and Shelf adapter.
version: 1.0.0
repository: https://github.com/PyFlat/Roomsocket

environment:
  sdk: ">=3.0.0 <4.0.0"

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter
  uuid: ^4.5.2
  shelf: ^1.4.2
  shelf_web_socket: ^3.0.0
  web_socket_channel: ^3.0.3
  stream_channel: ^2.1.4

dev_dependencies:
  lints: ^6.0.0
  shelf_router: ^1.1.4
  test: ^1.25.6
